### ISSUE TITLE
BGT Logo

### ISSUE THREAD

**Issue by flecno** [Binaergewitter/serious-bg#115]
da sich immernoch niemand gefunden hat, mal euer Logo als brauchbare Vektorgrafik zu exportieren hier nochmal der Aufruf:

**Gibt es einen Adobe Illustrator User, der es schafft das Logo in ein für das Web brauchbares SVG zu exportieren?**

Wenn man Retina Displays gewöhnt ist, verursacht das aktuelle Logo wirklich Augenkrebs!

**Comment by fliiiix** [comment]
Kann das beisteuern. War die source für die Sticker, falls das was hilft 
https://gist.githubusercontent.com/rundkorn/a40bd920df1727fdbfca/raw/ae4a555cff9579dda6183f588f1c03bca2b77372/bin%C3%A4rgewitter.svg

**Comment by ltsavar** [comment]
Die Ausgangslogos sind unter http://download.binaergewitter.de/logo/ zu finden. Die sind mit Illustrator erstellt worden. Fuer die Aufkleber haben wir auch noch mal ein neues SVG gemacht. Koennen wir das nehmen?
https://jit.cool/index.php/s/R3pbwYaax6pKzW8

**Comment by fliiiix** [comment]
@ltsavar wo sind die Ausgangslogos zu finden? http://download.binaergewitter.de/logo/ ist es nicht mehr

Vielleicht können wir ein Punkt media kit oder so unter 'Über uns' machen und das da verlinken.

**Comment by ltsavar** [comment]
@fliiiix doch gibts schon noch. Ist halt gerade nicht da weil wir noch nicht wieder auf @pfleidi s server umgestellt haben. 
Ansonsten siehe link zur jit.cloud  für das svg.
Aber ja wir können das auch als mediakit auf download.binaergewitter.de mit anbieten...

**Comment by fliiiix** [comment]
ach so kann man vielleicht die dinge die fehlen auch mal kopieren?

**Comment by sukramlitt** [comment]
Wäre auch was was für den Player super wäre das aktuelle Logo ist echt nicht so dolle aufgelöst

**Comment by tuxflo** [comment]
Fixed 186faa4e6206fc4257d00ca008ed554ba7837fce

**Comment by fliiiix** [comment]
yay stimmt das hier ist dann ja auch done :+1:
