### ISSUE TITLE
offline tag

### ISSUE THREAD

**Issue by ltsavar** [Binaergewitter/serious-bg#118]
Wäre gut wenn man im Head von einem Markdown Files einfach offline: 1 oder offline: true angeben könnte und die Seite dann nicht im Blog und in den Feeds angezeigt wird.
Klar kann man einen Artikel auch anders offline nehmen, aber diese Variante wäre auch mit nem Smartphone schnell mal machbar....

**Comment by rb2k** [comment]
Bäm, es gibt nun "published: true" oder "published: false"
Wenn man es nicht angibt dann ist der default auf true

**Comment by fliiiix** [comment]
keine Tests .___________.

**Comment by rb2k** [comment]
We're doing it live!

(Joa, sollte tests haben)

**Comment by ltsavar** [comment]
:+1:
