### ISSUE TITLE
disqus + ssl: Diese Seite versucht, Skripts aus nicht authentifizierten Quellen zu laden

### ISSUE THREAD

**Issue by makefu** [Binaergewitter/serious-bg#157]
In Chrome auf `https://blog.binaergewitter.de/<artikel>` laden Disqus Kommentare nicht, da diese via http ausgeliefert werden.

Siehe auch: https://support.google.com/chrome/answer/1342714

**Comment by ltsavar** [comment]
so schnell kanns gehen. vorgestern gings noch.
habs gerade auf https geändert, sollte also in ein paar stunden auf der webseite auch wieder gehen

**Comment by ltsavar** [comment]
ach nee quatsch nur der default ist nicht https
aber seit wir cloudflare haben geht eben auch https und ein paar urls waren nicht angepasst
