### ISSUE TITLE
Automatisch Cloudflare Cache Löschen nach Commit

### ISSUE THREAD

**Issue by ltsavar** [Binaergewitter/serious-bg#165]
Den Cache für die Hauptseite und für die Podcast URLs nach einem Travis run automatisch löschen.
Cloudflare hat ne API. @rb2k kann man das irgendwie einbinden?

**Comment by rb2k** [comment]
Kann man sicher :)
Ich denke "travis encrypt" auf der Kommandozeile + https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by ltsavar** [comment]
Klingt gut. Magst du das mal machen? :)

**Comment by rb2k** [comment]
Versuchen könnte man es, aber das ist halt kiloweise duct tape.
Es wäre besser wenn wir das caching auf "normal" zurückstellen und uns n besseres hosting zusammenfrickeln :)

Wenn wir einen provider von https://docs.travis-ci.com/user/deployment/ finden der klappt wäre das fetzig.

1. Openshift scheint irgendwie größer geworden zu sein was server angeht. Das letzte mal war es glaub zu wenig RAM: https://docs.travis-ci.com/user/deployment/openshift/
2. Eventuell kann @pfleidi mal schauen ob via https://docs.travis-ci.com/user/deployment/azure-web-apps was geht? Habt ihr Microsofties da zufällig gratis zeug?
3. Alternativ könnte man ja mal die Leute von exoscale(.ch) fragen und einen "powered by" dingens irgendwo anbringen.

Ich schau mir Openshift gerade mal an

**Comment by fliiiix** [comment]
@rb2k also wenn ich das nicht ganz falsch in Erinnerung habe ist das Problem mit openshift nur das es ein wenig gefrickel ist und altes ruby

Ich hab das mal mit http://developer.swisscom.com/ angeschaut und da ist halt 64 & 128 MB Ram zu wenig aber ich glaube ab 0.5GB sollte es laufen.

**Comment by rb2k** [comment]
Die haben nun n Ruby 2.0, das ist schonmal nahe dran, ich hab grad mal deployed, aber irgendwas will nicht. Evtl können wir einfach auf 2.0 downgraden und gut is

**Comment by rb2k** [comment]
Ah ja, richtig:

```
You have already activated rack 1.5.2, but your Gemfile requires rack 1.6.0. Using bundle exec may solve this. (Gem::LoadError)
  /opt/rh/ror40/root/usr/share/gems/gems/bundler-1.3.5/lib/bundler/runtime.rb:33:in `block in setup'
  /opt/rh/ror40/root/usr/share/gems/gems/bundler-1.3.5/lib/bundler/runtime.rb:19:in `setup'
  /opt/rh/ror40/root/usr/share/gems/gems/bundler-1.3.5/lib/bundler.rb:120:in `setup'
  /opt/rh/ror40/root/usr/share/gems/gems/bundler-1.3.5/lib/bundler/setup.rb:17:in `<top (required)>'
  /opt/rh/ruby200/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'
  /opt/rh/ruby200/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
  /opt/rh/ruby200/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'
  /opt/rh/ruby200/root/usr/share/gems/gems/passenger-4.0.18/lib/phusion_passenger/loader_shared_helpers.rb:212:in `run_load_path_setup_code'
  /opt/rh/ruby200/root/usr/share/gems/gems/passenger-4.0.18/helper-scripts/rack-loader.rb:69:in `load_app'
  /opt/rh/ruby200/root/usr/share/gems/gems/passenger-4.0.18/helper-scripts/rack-loader.rb:96:in `<module:App>'
  /opt/rh/ruby200/root/usr/share/gems/gems/passenger-4.0.18/helper-scripts/rack-loader.rb:4:in `<module:PhusionPassenger>'
  /opt/rh/ruby200/root/usr/share/gems/gems/passenger-4.0.18/helper-scripts/rack-loader.rb:3:in `<main>'
```

**Comment by rb2k** [comment]
Und selbst mit versions downgrade:

```
[ 2016-04-10 14:38:18.6415 516477/7f673c111700 Pool2/Implementation.cpp:1274 ]: [App 516549 stderr] [ 2016-04-10 14:38:18.6414 516549/0x000000018d3d70(Worker 1) utils.rb:74 ]: *** Exception Encoding::CompatibilityError in Rack application object (incompatible character encodings: UTF-8 and ASCII-8BIT) (process 516549, thread 0x000000018d3d70(Worker 1)):
```

Die haben das schon hart zerfrickelt... ich geb auf mit openshift :)

**Comment by rb2k** [comment]
So, nun läuft es auf IBM Bluemix ( O_O ) und zieht direkt von Github nach erfolgreichem commit: http://bgt.mybluemix.net

**Comment by rb2k** [comment]
Ich hab das caching mal wieder auf "normal" und dafür auf bluemix zeigen lassen
