### ISSUE TITLE
add duration to the rss feed

### ISSUE THREAD

**Issue by funkenstrahlen** [Binaergewitter/serious-bg#178]

**Comment by ltsavar** [comment]
@rb2k kriegen wir das irgendwie auf einfache Art hin? Ticket #177 sollte bisschen einfacher sein, da müsste man ja nur nen Head Request machen auf die Datei und das mit in den Feed eintragen.

Ohne Magic kriegt man die Länge der Folge wohl nicht raus...

@funkenstrahlen Wo ich dich gerade "sehe". Danke für die neue Xenim IOS App.

**Comment by rb2k** [comment]
Ich hab die Dateigröße mal via https://github.com/Binaergewitter/serious-bg/pull/180 hingefrickelt.
Länge in Sekunden ist etwas problematischer. Wir könnten das evtl hin-hacken da wir nun die dateigröße haben, aber dann müssten wir ne fixe bitrate annehmen. (oder jeweils n bissl runterladen und interpolieren)

**Comment by ltsavar** [comment]
oder wir gehen mal #81 an. dann könnte man darüber auch die Länge der Folge erhalten...

**Comment by rb2k** [comment]
Wie encoden wir denn? CBR, ABR, VBR?
Wenn wir das ziel wissen, können wir es temporär auch einfach hinhacken. Wenn wir 10-20 sekunden daneben liegen ist das wahrscheinlich nicht so schlimm :P

**Comment by ltsavar** [comment]
so this is also fixed now by #357
