### ISSUE TITLE
Matrix auf abo Seite erstellen

### ISSUE THREAD

**Issue by ltsavar** [Binaergewitter/serious-bg#2]
was man alles abonnieren kann

opus, mp3, bittorent, etc in jeweils all, talk, spezial

**Comment by ltsavar** [comment]
So das müssen wir jetzt mal wieder angehen.
Da wir talk,westcoast und spezial haben und das in verschiedenen Audioformaten. Wie machen wir das am besten? Ich würde auf feedburner einfach verzichten. Da guckt eh keiner von uns in die Statistiken und wer weiß ob das google nicht bald abschaltet.

**Comment by fliiiix** [comment]
:+1: für kein feedburner mehr, am einfachsten wohl einfach 3 (talk, spezial, westcoast) * Formate (opus, mp3, bittorent) feed 

Also so was wie
- binaergewitter_talk_opus.xml
- binaergewitter_talk_mp3.xml
- binaergewitter_talk_bittorent.xml
- binaergewitter_spezial_opus.xml
- binaergewitter_spezial_mp3.xml
- binaergewitter_spezial_bittorent.xml
- binaergewitter_westcoast_opus.xml
- binaergewitter_westcoast_mp3.xml
- binaergewitter_westcoast_bittorent.xml


Die interessante frage ist dann halt einfach wie iTunes, miro, Podcast.de damit klar kommen?
Und ob ein Kommentarfeed oder mehrere.

**Comment by rb2k** [comment]
Zumindest die links existieren schon alle:

http://blog.binaergewitter.de/podcast_feed/westcoast/mp3/rss.xml
http://blog.binaergewitter.de/podcast_feed/spezial/mp3/rss.xml
http://blog.binaergewitter.de/podcast_feed/talk/mp3/rss.xml


Andere Audio formate:
http://blog.binaergewitter.de/podcast_feed/talk/m4a/rss.xml
http://blog.binaergewitter.de/podcast_feed/talk/itunes/rss.xml (m4a wo möglich, sonst mp3)

Statt rss.xml geht auch atom.xml


Kommentarfeed gibt es einen kombinierten von disqus, wir hosten keine Kommentare :)

**Comment by pfleidi** [comment]
Hier ist mal ne erste Preview:

![image](https://cloud.githubusercontent.com/assets/118549/25309046/1fa69df6-2777-11e7-8927-21d362ba6506.png)

Weitere details gibts hier: https://github.com/Binaergewitter/serious-bg/pull/217

**Comment by pfleidi** [comment]
Ich würde das mittlerweile als erledigt ansehen. Dynamisch generieren ist aktuell out of scope.
