### ISSUE TITLE
spaactor verschlagwortet (audio to text)

### ISSUE THREAD

**Issue by Marwe** [Binaergewitter/serious-bg#220]
Stieß neulich auf spaactor und das Ergebnis der Audio-to-text-Konvertierung sah ganz brauchbar aus, schlug den Podcast daher vor. Inzwischen ist der Podcast mit Schlagworten (Text) durchsuchbar. Inwieweit die mit den ganzen Fachbegriffen klarkommen, ist noch genauer auszuloten.

Falls das nicht in Ordnung sein sollte, könnt ihr direkt dort Kontakt aufnehmen. 
Suche sieht so aus:
https://www.spaactor.com/search?mode=custom&selectedChannel=all&channel=4853d496-fcd1-4378-9b0e-5251bbf9acb8&period=complete&language=de&orWords=linux

**Comment by Marwe** [comment]
LOL, so muss sich das für die Großeltern anhören, die Missverständnisse sind viele und teils recht lustig ;)

**Comment by fliiiix** [comment]
Wollen wir das irgendwie noch Verlinken? (Ich hätte mal nein gesagt)

Sonst kann man diese issue schliessen.

:+1: danke @Marwe
