### ISSUE TITLE
Kalender/ical broken 

### ISSUE THREAD

**Issue by springzwerg** [Binaergewitter/serious-bg#221]
Kalender lässt sich nicht mehr abonnieren (OSX Sierra)

**Comment by fliiiix** [comment]
Wird der überhaut gepflegt?

**Comment by makefu** [comment]
Wir haben in der Sendung drüber geredet: Es braucht machine learning welches rät ob an einem Tag die sendung ist :D

**Comment by springzwerg** [comment]
Haha ja das argument fand ich geil 😄 
aber zum Live hören wäre es halt nice wenn man es 1/2 Tage vorher wüsste ;)

**Comment by makefu** [comment]
nen halben tag vorher versuchen eig immer wir via twitter zu announcen ;) wenn du ein bis zwei tage meinst ... uhhh da haben wir noch verbesserungspotential.

**Comment by ltsavar** [comment]
Ich hab die Kalender URLs von der Seite gelöscht. Die gibt es nicht mehr.
6a581dfbe642119c722163c98d796ada93066768

Wir bemühen uns die Termine rechtzeitig auf Twitter anzukündigen. In letzer Zeit haben wir durch Technikprobleme und Umbau leider selten Live senden können.
