### ISSUE TITLE
rss.xml kaputt

### ISSUE THREAD

**Issue by ltsavar** [Binaergewitter/serious-bg#229]
Mehrere Leute (via Twitter und Mail) haben sich beschwert dass die /rss.xml nicht mehr funktioniert. Ging wohl bis April 2017. Mir war bisher nicht bewusst das wir die haben. Problematisch ist, dass die auf der Hauptseite im Head verlinkt wird:
https://github.com/Binaergewitter/serious-bg/blob/master/serious/lib/site/views/layout.erb#L23

@rb2k: Hast du ne Idee ob man das fixen kann? Oder kann ich den Eintrag rausnehmen? Fällt uns das an anderer Stelle auf den Fuß?

Grüße

**Comment by rb2k** [comment]
Sollten beide gehen.

Code ist hier:
https://github.com/Binaergewitter/serious-bg/blob/master/serious/lib/serious.rb

Bin grad ohne Laptop am Flughafen
