### ISSUE TITLE
BGT links with / at the end (from disqus) broken

### ISSUE THREAD

**Issue by madmas** [Binaergewitter/serious-bg#232]
Currently, link with an / seem to be broken:

Not working: http://blog.binaergewitter.de/2017/01/21/binaergewitter-talk-number-164-steckerchecker/

working: http://blog.binaergewitter.de/2017/01/21/binaergewitter-talk-number-164-steckerchecker

Those with / at then end are rendered from Disqus. If you click on one of the "Auch auf Binärgewitter Podcast" suggestions, you end up on the error page.

**Comment by rb2k** [comment]
This needs a slash at the end:

https://github.com/Binaergewitter/serious-bg/blob/995d0e96815ba35ba64449ad6ef59585cb116098/serious/lib/serious.rb#L249

**Comment by madmas** [comment]
Cool, thanks a lot. Couldn't find it quick enough 😇
