### ISSUE TITLE
Lizenz? =)

### ISSUE THREAD

**Issue by sukramlitt** [Binaergewitter/serious-bg#270]
Hi,
würd ja gern mal euren kram test weise forken etc, aber ohne Lizenz naja.. Wollt ihr nicht irgendwas auf das Repo schmeißen? 

Grad so mit blick auf das Hacktoberfest.

**Comment by sukramlitt** [comment]
Andererseits macht das irgendwie auch null sinn. ich will euren kram ja nicht nutzen/verbreiten. vergesst was ich gesagt habe.

Andere Frage:
Habt ihr schonmal über hugo als static site generator nachgedacht/intersse?

**Comment by rb2k** [comment]
Gedacht ja, aber die Podcast RSS/Atom Sachen neu frickeln ist immer nervig. Meist funktioniert der “neue markdown Datei” + travis + heroku deployment workflow bei alternativen auch nicht so elegant.

Prinzipiell ist die aktuelle Lösung schon gekrepelt, aber auch quasi ohne maintenance und kosten :)

**Comment by ltsavar** [comment]
Alle Inhalte stehen unter Creative Commons BY-SA.
Was mit dem Code ist muss @rb2k sagen. Von mir aus kann das unter eine BSD Lizenz.

**Comment by fliiiix** [comment]
Also serious worauf es ja aufgebaut ist hat eine MIT Lizenz https://github.com/Binaergewitter/serious-bg/blob/master/serious/LICENSE

Von daher würde ich wohl den rest den wir dazu gekrepelt haben auch unter MIT stellen.

**Comment by fliiiix** [comment]
https://github.com/Binaergewitter/serious-bg/commit/7ab12be39c95cd95f07fdc50aea88b2bd8a35936
