### ISSUE TITLE
Update Podlove Player

### ISSUE THREAD

**Issue by ltsavar** [Binaergewitter/serious-bg#271]
Unser Webplayer müsste dringend mal geupdatet werden....

**Comment by fliiiix** [comment]
Der Podlove Web Player 4.0 https://docs.podlove.org/podlove-web-player/ könnte man integrieren.

**Comment by sukramlitt** [comment]
Jo, also ich würd ja mal gern daran rumfrickeln nun ist mein Problem das ich null ruby erfahrung habe. Ich versuche mich gerade mit dem Buildsystem auseinander zu setzen. Frage -> könnt ihr evtl nen Dockerfile und die zwei commands für test/run bereitstellen. Damit ich schonmal den generator starten kann ohne nen udemy kurs für ruby zu belegen =)?

**Comment by sukramlitt** [comment]
```
FROM ruby:2.5.1
ADD . /src
WORKDIR /src

RUN bundle install --jobs=3 --retry=3 --deployment --path=vendor/bundle
RUN bundle exec rake
```

Das wäre mein erster versuch (aus travis-ci extrahiert) leider mit folgendem issue im rake:
```
Step 5/5 : RUN bundle exec rake
 ---> Running in c8d131c84320
/usr/local/bin/ruby -w -I"lib:test" -I"/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib" "/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb" "tests/smoke_test.rb"
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:559: warning: instance variable @new_platform not initialized
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:535: warning: instance variable @new_platform not initialized
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:535: warning: instance variable @new_platform not initialized
/src/vendor/bundle/ruby/2.5.0/gems/feedvalidator-0.2.1/lib/feed_validator/assertions.rb:71: warning: mismatched indentations at 'end' with 'begin' at 62
/src/vendor/bundle/ruby/2.5.0/gems/addressable-2.5.2/lib/addressable/idna/pure.rb:154: warning: assigned but unused variable - startercc
/src/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:36:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
        from /src/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:36:in `parse_file'
        from /src/tests/smoke_test.rb:8:in `<top (required)>'
        from /src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:17:in `require'
        from /src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:17:in `block in <main>'
        from /src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `select'
        from /src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `<main>'
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib" "/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb" "tests/smoke_test.rb" ]
/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
The command '/bin/sh -c bundle exec rake' returned a non-zero code: 1
```

Erwartungsgemäß ist mir natürlich teilweise unklar was hier passiert. Any suggestions? Ansonsten popel ich mal rum..

**Comment by fliiiix** [comment]
:tada: klingt gut ich mach mich nacher mal daran das in ein docker dingsi zu packen

**Comment by fliiiix** [comment]
ping @sukramlitt ein work in progress Dockerfile findest du hier: https://github.com/Binaergewitter/serious-bg/pull/276

```
docker build -t blog . && docker run -p 9292:9292 blog
```
Die relevanten files für den payer sind so:
* der live on air player: https://github.com/Binaergewitter/serious-bg/blob/master/serious/lib/site/views/_live.erb
* der reguläre player: https://github.com/Binaergewitter/serious-bg/blob/master/serious/lib/site/views/_podcast_controls.erb
- css & js kram in https://github.com/Binaergewitter/serious-bg/tree/master/serious/lib/site/public/podlove-web-player und https://github.com/Binaergewitter/serious-bg/tree/master/serious/lib/site/public/mediaelement der vermutlich weg kann

**Comment by sukramlitt** [comment]
@fliiiix works for me. Ich schau dann mal was ich als k8s/DevOp so am frontend ausrichten kann ^^

**Comment by sukramlitt** [comment]
@fliiiix   #277 
bitte schau dir mal  #277 an und sag mir wie du es grundsätzlich findest.
Für mich ist es aktuell noch ein Problem das euer Content nicht zu dem fließtext passt den der player erwartet, Die Frage ist wie gehen wir damit um, wir könnten für alte folgen die klassische Ansicht rendern also als plain html + neuer player. Oder diese Ansicht bleibt der detail view vorbehalten. 

Man könnte ja den kontent der letzten n folgen anpassen so das es im player mehr Sinn macht.
Alternative können wir auch einfach das alte layout für den conent behalten.

**Comment by sukramlitt** [comment]
und wann wandert das in prod =)?

**Comment by sukramlitt** [comment]
okay instant ^^. Hoffe es gefällt soweit

eine Sache ist defentive noch offen: die file sizes im download ist immer 100mb weil ihr keine angebt. Ansonsten bitte bugs melden ich schau dann drauf

**Comment by fliiiix** [comment]
@rb2k oder @pfleidi habt ihr vorschläge wie man die filesize am besten bekommt?

**Comment by sukramlitt** [comment]
Evtl. Script ich das nachher schnell runter..

**Comment by sukramlitt** [comment]
#279 kleine fix für die responsive ui

**Comment by fliiiix** [comment]
@sukramlitt das ist noch ein bug oder? 

![2018-10-02--1538485651_3200x1800](https://user-images.githubusercontent.com/1682954/46350514-3e078480-c655-11e8-9564-4820e48289f4.png)

**Comment by ltsavar** [comment]
Ja die Info haben wir nicht bzw. hat noch nie jemand gebaut
Siehe auch #178
das müsste man berechnen....
Alternativ gibt es zu den letzten 100 Sendungen oder mehr immer eine .json Datei:
http://download.binaergewitter.de/2016-09-01.Binaergewitter.Talk.156.json
Da steht auch die Länge drin....

**Comment by fliiiix** [comment]
Joa die letzen 100 reichen glaub ich dann kann man was bauen was jeweils die Länge mit js aus dem file holt

**Comment by sukramlitt** [comment]
@fliiiix Danke für den schönen Twitter post. Ich schaue Mal ob ich die Woche noch Zeit finde für die Spieldauer. Aber wenn das erstmal das einzige ist dann bin ich schonmal ganz zufrieden.

**Comment by fliiiix** [comment]
#281 ist noch offen aber der neue player ist migriert und läuft :tada:
