### ISSUE TITLE
Implement duration in new podlove-web-player v4

### ISSUE THREAD

**Issue by dev-matil** [Binaergewitter/serious-bg#281]
Der neue Player bietet die möglichkeit die Dauer einer Episode anzuzeigen.

Die dauer kann den auphonic metadaten entnommen werden
Beipspiel:
http://download.binaergewitter.de/2016-09-01.Binaergewitter.Talk.156.json

Aus javascript kann der Zugriff aktuell nicht erfolgen da ein CORS Header gesetzt werden muss.
(von blog.binaergewitter.de auf download.binaergewitter.de)

**Grundsätzlich überlegungen**
Es gibt insgesamt ein Design Problem in der Anwendung.

Beipspiel RSS Feed:
Ein call auf den Feed erzeugt 4 subsequent calls an die download api um die file sizes zu ermitteln.
Das selbige gilt auch für den neuen Player. Jedes file erzeugt einen header call zur ermittelung der file size. Das ist zwar bei der geringen load den die Seite hat kein großes Problem aber erzeugt unnötig viel Last. 

Hieraus ergibt sich für mich folgende Frage:
Anstatt wie bisher sämtlichen Content live zu rendern wäre es eine Option auf statischen Content zu wechseln. Mann könnte themen wie das erzeugen der nötigen Metadaten deutlich leichter in einem Schritt vor dem starten des Webservers erreichen. So könnten die unterschiedlichen Datenquellen zusammengefasst werden, um z.b. eine Episode-123.json zu erzeugen die alle Informationen bündelt und welche dann statisch ausgeliefert wird.

**Comment by rb2k** [comment]
Ich kann mich nicht mehr 100 % genau daran erinnern, aber ich dachte wir haben für die calls etwas caching, so dass es nur einmal pro Neustart passiert?

(Ich glaub der commit hatte „horrible hack“ im Kommentar,  kann also gut sein dass es nicht so ist :D)

**Comment by sukramlitt** [comment]
ich fürchte da cached garnichts :). Wiegesagt das ist ja auch kein Thema. Ihr habt ja auch kaum last.
Aber Grunsätzlich stellt sich mir die Frage ob live rendering evtl. Teil des Problems ist. Das macht die Pipeline immer komplizierter da alles in der Runtime passieren muss. Keine Ahnung ob ich richtig liege :).   @rb2k hast du ne Ahnung ob ihr CORS header setzten könnt. Dann kann man das ganze zummindest auf dem frickelpfad beenden.

**Comment by sukramlitt** [comment]
ah cloudflare hängt da noch. Das ist für mich natürlich alles schwer zu durchschauen da es nicht dokumentiert ist wie euer Deployment aussieht. Aber lass uns mal CORS versuchen und dann schau ich mal das ich das erstmal im JS rausparse. Kannst du den Change dafür machen?

**Comment by fliiiix** [comment]
Ich glaube dit hier https://github.com/Binaergewitter/serious-bg/commit/7209eabf2adccc17f208486a61dc5484aee1c057#diff-7fbae86a868862c038b49995534b084aR101 ist der caching layer für den feed 

aber ja wenn wir mal ein besseres system haben, wär das schon erstrebenswert :D

**Comment by fliiiix** [comment]
Ich weiss nicht vielleicht könne wir die infos auch einfach mal im ruby teil requesten und cachen dann kann man die info auch statisch renderen, weil ändern sich ja eigentlich nicht

**Comment by sukramlitt** [comment]
Das wäre auch super

**Comment by sukramlitt** [comment]
Das wäre auch super

**Comment by sukramlitt** [comment]
Fuck ausversehen geclosed

**Comment by sukramlitt** [comment]
Da ich auf ruby seite nicht weiter komme habe ich einfach mal einen komplett anderen Ansatz verfolgt um das Problem zu lösen #282

Sagt mal was ihr davon haltet.

**Comment by fliiiix** [comment]
this is fixed since: https://github.com/Binaergewitter/serious-bg/commit/1c75484cfd88234f11bb0c8acb7d0aaf08a0982b
