### ISSUE TITLE
Implement duration for podcast feed 

### ISSUE THREAD

**Issue by ltsavar** [Binaergewitter/serious-bg#354]
z.B. bei amazon music (aber sicher auch bei mehreren anderen) wird der podcast mit 0 sekunden länge angezeigt.

Wir müssten die Länge mit in den Feed schreiben

Siehe auch #281

**Comment by fliiiix** [comment]
Also hmm es steht eigentlich eine lenght im feed see
```
<enclosure url="http://download.binaergewitter.de/2021-09-20.Binaergewitter.Talk.284.mp3" length="103082824" type="audio/x-mp3"/>
```

wie müsste das dann richtig sein?

**Comment by ltsavar** [comment]
hmm gute Frage
bei anderen podcast ist es audio/mpeg statt audio-/x-mp3 ... könnten wir mal umstellen

ansonsten gibt es zwar noch
<itunes:duration>00:34:00</itunes:duration>
bei vielen, aber ich hoffe das braucht man nicht unbedingt....

**Comment by ltsavar** [comment]
aber wahrscheinlich ist es das schon und wir müssten uns die duration aus dem .json file berechnen und eintragen
wüsste nicht wie wir das sonst machen können

**Comment by ltsavar** [comment]
auch eine <itunes:summary> müssten wir wohl reintun damit amazon musik und co was anzeigen unter der episode
normalerweise würde sich der 1. Satz vom Blogpost dafür eignen...

**Comment by fliiiix** [comment]
Google hat wenigstens so was https://support.google.com/podcast-publishers/answer/9889544?hl=en fuer amazon finde ich da nix

**Comment by ltsavar** [comment]
ist alles das gleiche. wir brauchen wohl itunes duration...
