### ISSUE TITLE
Deezer link is broken

### ISSUE THREAD

**Issue by fliiiix** [Binaergewitter/serious-bg#355]
https://blog.binaergewitter.de/pages/abonnieren

**Comment by ltsavar** [comment]
gemein die haben unseren podcast gelöscht

**Comment by ltsavar** [comment]
hab versucht unseren Feed neu hinzuzufügen aber der war schon drin?!
also muss ich wohl über den support gehen oh man das kann dauern

**Comment by fliiiix** [comment]
Ok dann schau mal mit den support oder wir nehmen das raus keine ahnung ob jemand deezer braucht xD

**Comment by fliiiix** [comment]
![image](https://user-images.githubusercontent.com/1682954/142729251-54a9fdcf-40a5-471c-9c6a-9cf8250c8f29.png)


Vielleicht sollten wir sowieso hier iTunes und co aus der liste nehmen und die unterhalb der table listen mit amazone und google und co ich nehem an die liste ist mit diesen 3 eh nicht complet oder?

**Comment by ltsavar** [comment]
nee darunter listen würde ich es nicht. dann findet man es nicht.
aber ja die Liste ist nicht abschließend.
vielleicht eher in den podlove abo button einbauen...

**Comment by fliiiix** [comment]
Agree to disagree i guess

**Comment by fliiiix** [comment]
any updates @ltsavar ? sonst remove ich den deezer link

**Comment by ltsavar** [comment]
Ja mach


Am 6. März 2022 18:15:57 MEZ schrieb Felix ***@***.***>:

**Comment by fliiiix** [comment]
fixed in https://github.com/Binaergewitter/serious-bg/commit/20c10a22d6c329eb6c4f2178108c566882906000 and https://github.com/Binaergewitter/serious-bg/commit/00ee869a80b043f36a822d9a442c7bba11603870
