### ISSUE TITLE
Amazone does not show summary

### ISSUE THREAD

**Issue by fliiiix** [Binaergewitter/serious-bg#356]
@ltsavar: https://github.com/Binaergewitter/serious-bg/issues/354#issuecomment-967800945

> auch eine itunes:summary müssten wir wohl reintun damit amazon musik und co was anzeigen unter der episode

Machen wir aktuell muss also ein anderes problem sein: 

![image](https://user-images.githubusercontent.com/1682954/142722622-161d6b5f-47dc-4395-a50d-98a620290da2.png)

**Comment by fliiiix** [comment]
Ich kann probieren ob eine description hilft

**Comment by ltsavar** [comment]
strange.
ja mach mal bitte.
einfach genau so wie summary.

warum ist das pub date eigentlich mit 0 Uhr gesetzt?
