### ISSUE TITLE
RSS Feed broken input?

### ISSUE THREAD

**Issue by fliiiix** [Binaergewitter/serious-bg#363]
via blog: http://blog.binaergewitter.de/2022/01/15/binaergewitter-talk-number-289-razzia-im-chatraum/#isso-2018
Im RSS feed ist die 4. page kaputt: https://blog.binaergewitter.de/podcast_feed/all/mp3/rss.xml?&page=4

**Comment by rb2k** [comment]
Könnten wir. Oder wir reduzieren einfach den cache / concurrency.
Ich glaub die letzten paar addons (?chapter marks?) werden immer in den cache gepackt aber nie rausgeworfen :)

**Comment by rb2k** [comment]
Ich hab mal RUBY_GC_HEAP_GROWTH_FACTOR auf 1.03 gesetzt in den heroku ENV vars.
Das hilft normalerweise nur wenn wir ganz knapp drüber sind, aber mal schauen :)

**Comment by rb2k** [comment]
Hm, scheint tatsächlich nur page 4 zu sein. Da ist irgendwas kaputt... evtl n typo und er läd die mp3 statt den chapter marks oder irgendwas komisches. Müsste man mal lokal testen was er da alles einzieht.

**Comment by rb2k** [comment]
Geht:

https://blog.binaergewitter.de/rss.xml?&page=4&feed_size=43

Geht nicht:
https://blog.binaergewitter.de/rss.xml?&page=4&feed_size=44

**Comment by rb2k** [comment]
Geht:
https://blog.binaergewitter.de/rss.xml?&page=0&feed_size=217

Geht nicht:
https://blog.binaergewitter.de/rss.xml?&page=0&feed_size=218

**Comment by ltsavar** [comment]
Danke fürs raussuchen.
Auf den ersten Blick sehe ich jedenfalls kein Problem mit der yaml Datei. Muss also echt was komisches sein...

**Comment by rb2k** [comment]
> Danke fürs raussuchen.
> Auf den ersten Blick sehe ich jedenfalls kein Problem mit der yaml Datei. Muss also echt was komisches sein...

Ist auch komisch dass er das nur im RSS feed hasst. Ich denke der code der versucht irgend ein RSS Element zu generieren krepelt hart in nem externen http request

**Comment by fliiiix** [comment]
also gut ich schaus mir halt an :D
