### ISSUE TITLE
add alternate feeds

### ISSUE THREAD

**Issue by ltsavar** [Binaergewitter/serious-bg#5]
would be nice having also the alternate-feeds in each feed

see http://podlove.org/alternate-feeds/

**Comment by pfleidi** [comment]
Correct me if I'm wrong, but: As far as I know, most people are using podcast directories provided by their apps to subscribe to podcasts. Also: Are there any clients that actually support it?

I think that at the moment, nobody is going to work on this. Do we want to close it?

**Comment by rb2k** [comment]
Sounds reasonable
